routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PromotionController@index");
Route::resource("student", "StudentController");
Route::resource("promotion", "PromotionController");
Route::resource("module", "ModuleController");

Route::post("promotion/storemodules", "PromotionController@storeModules")
    ->name("promotion.store_modules");

Route::post("student/storemodules", "StudentController@storeModules")
    ->name("student.store_modules");

app/Promotion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Promotion extends Model
{
    protected $fillable = ['name', 'speciality'];

    public function students() {
        return $this->hasMany(Student::class);
    }

    public function modules() {
        return $this->belongsToMany(Module::class);
    }
}

app/Http/Controllers/PromotionController.php
<?php

namespace App\Http\Controllers;

use App\Promotion;
use App\Student;
use App\Module;
use Illuminate\Http\Request;

class PromotionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) 
    {
        $search = $request->get("search");
        if ($search) {
            $promotion = Promotion::where('name', 'like', '%' . $search . '%')
            ->orWhere('speciality', 'like', '%' . $search . '%')
            ->get();
        // } elseif ($search) {
        //     $student = Student::where('lastname', 'like', '%' . $search . '%')
        //     ->orWhere('firstname', 'like', '%' . $search . '%')
        //     ->get();
        // }elseif ($search) {
        //     $module = Module::where('name', 'like', '%' . $search . '%')
        //     ->get();
        } else {
          $promotion = Promotion::all();
        //   $student = Student::all();
        //   $module = Module::all();
        }

        // return view("promotion.index", ["promotions" => $promotion, "students" => $student, "modules" => $module, "search" => $search]);
        return view("promotion.index", ["promotions" => $promotion, "search" => $search]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("promotion.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $promotion = new Promotion();
        $promotion->name = $request->input("name");
        $promotion->speciality = $request->input("speciality");
        $promotion->save();

        return redirect()->action([PromotionController::class, 'index']);
    }

    public function storeModules(Request $request)
    {
        $promotion = Promotion::find($request->input("promotion_id"));
        $promotion->modules()->detach();
        $promotion->modules()->attach($request->input("modules"));

        return redirect()->route("module.index", ["promotion" => $promotion->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function show(Promotion $promotion)
    {
        return view("promotion.show", ["promo" => $promotion]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function edit(Promotion $promotion)
    {
        return view("promotion.edit", ["promo" => $promotion]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Promotion $promotion)
    {
        $promo = Promotion::find($promotion->id);
        $promo->update([
            "name" => $request->input("name"),
            "speciality" => $request->input("speciality"),
        ]);

        return redirect()->action([PromotionController::class, 'index']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function destroy(Promotion $promotion)
    {
        $promotion->students()->delete();
        // $promotion->modules()->delete();
        $promotion->delete();
        return redirect()->action([PromotionController::class, 'index']);
    }
}

resources/views/promotion/create.blade.php
@extends('promotion.form')
@section('page-title')
    Create Promotion
@endsection
@section('action'){{ route('promotion.store') }}@endsection

resources/views/promotion/edit.blade.php
@extends("promotion.form")

@section('page-title')
    Edit Promotion
@endsection

@section('action'){{ route('promotion.update', $promo) }}@endsection

@section("method")@method("PUT")
@endsection

@section("name"){{ $promo->name }}
@endsection

@section("speciality"){{ $promo->speciality }}
@endsection

resources/views/promotion/form.blade.php
@extends('application')
@section('page-title')
  @yield('page-title')
@endsection
@section('page-content')
  <div class="container mb-5 mt-3">
    <form method="post" action="@yield('action')">
      @yield('method')
      @csrf
        <div class="form-group">
          <label for="name">Promo Name</label>
          {{-- <input type="text" class="form-control" name="name" id="name" value="@yield("name")"> --}}
          <select class="form-control" name="name" id="name">
            <option>B1</option>
            <option>B2</option>
            <option>B3</option>
            <option>M1</option>
            <option>M2</option>
          </select>
        </div>
        <div class="form-group">
          <label for="speciality">Speciality</label>
          {{-- <input type="text" class="form-control" name="speciality" id="speciality" value="@yield("speciality")"> --}}
          <select class="form-control" name="speciality" id="speciality">
            <option>Computer Science</option>
            <option>Robotics & Systems Engineering</option>
            <option>Marketing Communication</option>
            <option>Audiovisual</option>
            <option>3D Animation Video games</option>
            <option>Creation Design</option>
          </select>
        </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
@endsection

resources/views/promotion/index.blade.php
@extends('application')
@section('page-title')
    List
@endsection
@section('page-content')
    <div class="container">
        @if($search)
            <p class="mt-3">Search result for: {{ $search }}</p>
            <a href="{{route("promotion.index")}}" class="mb-5">Return to list</a>
        @endif
    </div>
    <div class="container">

        <a class="btn btn-outline-success mt-3" href="{{ route("promotion.create") }}">Add Promotion</a>

        <table class="table table-bordered mt-3">
            <thead>
            <tr>
                <th scope="col">Promo Name</th>
                <th scope="col">Speciality</th>
                <th scope="col">Students List</th>
                <th scope="col">Modules List</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>

            @foreach($promotions as $promo)
                <tr>
                    <td>{{ $promo->name }}</td>
                    <td>{{ $promo->speciality }}</td>
                    <td>
                        @foreach($promo->students as $stud)
					        <li class="list-group" aria-current="true">{{ $stud->lastname." ".$stud->firstname }}</li>
                        @endforeach
                    </td>
                    <td>
                        @foreach($promo->modules as $modu)
					        <li class="list-group" aria-current="true">{{ $modu->name }}</li>
                        @endforeach
                    </td>
                    
                    <td class="d-flex" style="size: inherit">
                        <a class="btn btn-outline-success mr-2" href="{{ route("promotion.show", $promo) }}">Show</a>
                        <a class="btn btn-outline-info mr-2" href="{{ route("promotion.edit", $promo) }}">Edit</a>
                        <form action="{{ route("promotion.destroy", $promo->id) }}" method="post">
                            <input class="btn btn-outline-danger" type="submit" value="Delete"/>
                            @method('delete')
                            @csrf
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
@endsection

resources/views/promotion/show.blade.php
@extends('application')
@section('page-title')
  {{ $promo->name }}
@endsection

@section('page-content')
  <div class="container">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ $promo->name }} - {{ $promo->speciality }}</h5>
        <p class="card-text">
          <strong>Students promotion: </strong>
        </p>
        <ul class="list-group list-group-flush mb-3">
            @foreach($promo->students as $stud)
                <li class="list-group-item">
                    <a href="{{ route("student.show", $stud) }}">{{ $stud->lastname." ".$stud->firstname }}</a>
                </li>
            @endforeach
        </ul>
        <p class="card-text">
          <strong>Modules promotion: </strong>
        </p>
        <ul class="list-group list-group-flush mb-3">
            @foreach($promo->modules as $modu)
                <li class="list-group-item">
                    <a href="{{ route("module.show", $modu) }}">{{ $modu->name." ".$modu->speciality }}</a>
                </li>
            @endforeach
        </ul>
        <div class="d-flex">
            <a class="btn btn-outline-primary mr-2" href="{{ route("student.create", ["promotion"=>$promo]) }}">Add Student</a>
            <a class="btn btn-outline-primary mr-2" href="{{ route("module.index", ["promotion"=>$promo]) }}">Add Modules</a>
            <a class="btn btn-outline-info mr-2" href="{{ route("promotion.edit", $promo) }}">Edit</a>
            <form action="{{ route("promotion.destroy", $promo->id) }}" method="post">
                <input class="btn btn-outline-danger" type="submit" value="Delete"/>
                @method('delete')
                @csrf
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection