routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PromotionController@index");
Route::resource("student", "StudentController");
Route::resource("promotion", "PromotionController");
Route::resource("module", "ModuleController");

Route::post("promotion/storemodules", "PromotionController@storeModules")
    ->name("promotion.store_modules");

Route::post("student/storemodules", "StudentController@storeModules")
    ->name("student.store_modules");

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Module extends Model
{
    public function promotions(): BelongsToMany {
        return $this->belongsToMany(Promotion::class);
    }

    public function students(): BelongsToMany {
        return $this->belongsToMany(Student::class);
    }
}

app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Module;
use App\Promotion;
use App\Student;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request): View
    {
        $search = $request->get("search");
        if ($search) {
            $module = Module::where('name', 'like', '%' . $search . '%')
            ->orWhere('description', 'like', '%' . $search . '%')
            ->get();
        // } elseif ($search) {
        //     $promotion = Promotion::where('name', 'like', '%' . $search . '%')
        //     ->orWhere('speciality', 'like', '%' . $search . '%')
        //     ->get();
        // }elseif ($search) {
        //     $student = Student::where('lastname', 'like', '%' . $search . '%')
        //     ->orWhere('firstname', 'like', '%' . $search . '%')
        //     ->get();
        } else {
            $module = Module::all();
            // $promotion = Promotion::all();
            // $student = Student::all();
        }

        // return view("module.index", ["modules" => $module, "promotions" => $promotion, "student" => $student, "search" => $search, "current_promotion_id" => $request->get("promotion"), "current_student_id" => $request->get("student"), "modules" => Module::all()]);
        return view("module.index", ["modules" => $module, "search" => $search, "current_promotion_id" => $request->get("promotion"), "current_student_id" => $request->get("student")]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request): View
    {
        return view(
            "module.create",
            [
                "promotions" => Promotion::all(),
                "students" => Student::all(),
                "current_promotion_id" => $request->input("promotion_id"),
                "current_student_id" => $request->input("student_id")
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request): RedirectResponse
    {
        $newModule = new Module();
        $newModule->name = $request->input("name");
        $newModule->description = $request->input("description");
        $newModule->save();

        $newModule->promotions()->attach($request->input("promotions"));
        $newModule->students()->attach($request->input("students"));

        return redirect()->route(
            "module.index",
            [
                "promotion" => $request->get("promotion_id"),
                "student" => $request->get("student_id")
            ]
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function show(Module $module): View
    {
        return view("module.show", ["current_module" => $module]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module): View
    {
        return view("module.edit",
            [
                "promotions" => Promotion::all(),
                "students" => Student::all(),
                "editing_module" => $module,
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Module $module): RedirectResponse
    {
        $module->name = $request->input("name");
        $module->description = $request->input("description");
        $module->promotions()->detach();
        $module->students()->detach();
        $module->promotions()->attach($request->input("promotions"));
        $module->students()->attach($request->input("students"));
        $module->save();

        return redirect()->route("module.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function destroy(Module $module): RedirectResponse
    {
        $module->delete();
        return redirect()->route("module.index");
    }
}

resources/views/module/create.blade.php
@extends("module.form")
@section("title")Create Module @endsection
@section("action")
	{{ route("module.store", ["promotion_id" => $current_promotion_id, "student_id" => $current_student_id]) }}
@endsection
@section("promotions-list")
	@foreach($promotions as $promotion)
		<div class="mb-3 form-check">
			<input type="checkbox" class="form-check-input" id="promotion-{{ $promotion->id }}"
						 value="{{ $promotion->id }}" name="promotions[]"
						 	@if($current_promotion_id != null && $promotion->id == $current_promotion_id) checked @endif>
			<label class="form-check-label" for="promotion-{{ $promotion->id }}">{{ $promotion->name." ".$promotion->speciality }}</label>
		</div>
	@endforeach
@endsection
@section("students-list")
	@foreach($students as $student)
		<div class="mb-3 form-check">
			<input type="checkbox" class="form-check-input" id="student-{{ $student->id }}"
						 value="{{ $student->id }}" name="students[]"
						 	@if($current_student_id != null && $student->id == $current_student_id) checked @endif>
			<label class="form-check-label" for="student-{{ $student->id }}">{{ $student->lastname." ".$student->firstname }}</label>
		</div>
	@endforeach
@endsection

resources/views/module/edit.blade.php
@extends("module.form")
@section("title")Edit Module @endsection
@section("action"){{ route("module.update", $editing_module) }} @endsection
@section("method") @method("PUT") @endsection
@section("name"){{ $editing_module->name }}@endsection
@section("description"){{ $editing_module->description }} @endsection
@section("promotions-list")
	@foreach($promotions as $promotion)
		<div class="mb-3 form-check">
			<input type="checkbox" class="form-check-input" id="promotion-{{ $promotion->id }}"
						 value="{{ $promotion->id }}" name="promotions[]"
						 	@foreach($editing_module->promotions as $module_promotion)
						 		@if($module_promotion->id == $promotion->id) checked @endif
						 	@endforeach
			>
			<label class="form-check-label" for="promotion-{{ $promotion->id }}">{{ $promotion->name." ".$promotion->speciality }}</label>
		</div>
	@endforeach
@endsection
@section("students-list")
	@foreach($students as $student)
		<div class="mb-3 form-check">
			<input type="checkbox" class="form-check-input" id="student-{{ $student->id }}"
						 value="{{ $student->id }}" name="students[]"
						 	@foreach($editing_module->students as $module_student)
						 		@if($module_student->id == $student->id) checked @endif
						 	@endforeach
			>
			<label class="form-check-label" for="student-{{ $student->id }}">{{ $student->lastname." ".$student->firstname }}</label>
		</div>
	@endforeach
@endsection

resources/views/module/form.blade.php
@extends('application')
@section('page-title')
	@yield("title")
@endsection
@section('page-content')
	@if(!isset($current_promotion_id)) {{ $current_promotion_id = null }}  @endif
	<div class="container">
		<form method="POST" action="@yield("action")">
			@csrf
			@yield("method")
			<div class="mb-3">
				<label for="name" class="form-label">Module Name</label>
				<input type="text" class="form-control" id="name" name="name" value="@yield("name")">
			</div>
			<div class="mb-3">
				<label for="description" class="form-label">Description</label>
				<input type="text" class="form-control" id="description" name="description" value="@yield("description")">
			</div>
			<div class="mb-3">
			<label for="name" class="form-label">Promotions List</label>
			@yield("promotions-list")
			</div>
			<div class="mb-3">
			<label for="name" class="form-label">Students List</label>
			@yield("students-list")
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
@endsection

resources/views/module/index.blade.php
@extends('application')
@section('page-title')Modules @endsection
@section('page-content')
  <div class="container">
    @if($search)
      <p class="mt-3">Search result for: {{ $search }}</p>
      <a href="{{route("module.index")}}" class="mb-5">Return to list</a>
    @endif
  </div>
  <div class="container">
    @if(isset($current_module_id))
      @include("module.parts.form_create")
    @else
      @include("module.parts.list")
    @endif
  </div>
@endsection

resources/views/module/show.blade.php
@extends("application")

@section("page-title")
	{{ $current_module->name }}
@endsection
@section("page-content")
	<div class="container d-flex justify-content-center">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">{{ "Module : ".$current_module->name }}</h5>
				<h6 class="card-subtitle mb-2 text-muted">{{ "Description : ".$current_module->description }}</h6>
				<p class="mt-5">Promotions accessing the module:</p>
				<ul class="list-group mb-5">
					@foreach($current_module->promotions as $module_promotion)
						<li class="list-group-item" aria-current="true">{{ $module_promotion->name }}</li>
					@endforeach
				</ul>
				<p class="mt-5">Students accessing the module:</p>
				<ul class="list-group mb-5">
					@foreach($current_module->students as $module_student)
						<li class="list-group-item" aria-current="true">{{ $module_student->lastname." ".$module_student->firstname }}</li>
					@endforeach
				</ul>

				<div class="d-flex">
					<a href="{{ route("module.edit", $current_module) }}"
						 class="btn btn-outline-info card-link mr-3">Edit</a>
					<form action="{{ route("module.destroy", $current_module) }}" method="post">
						<input class="btn btn-outline-danger" type="submit" value="Delete"/>
						@method('delete')
						@csrf
					</form>
				</div>

			</div>
		</div>
	</div>
@endsection