routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "PromotionController@index");
Route::resource("student", "StudentController");
Route::resource("promotion", "PromotionController");
Route::resource("module", "ModuleController");

Route::post("promotion/storemodules", "PromotionController@storeModules")
    ->name("promotion.store_modules");

Route::post("student/storemodules", "StudentController@storeModules")
    ->name("student.store_modules");

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['lastname', 'firstname', 'email'];

    public function promotion() {
        return $this->belongsTo(Promotion::class);
    }

    public function modules() {
        return $this->belongsToMany(Module::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use App\Promotion;
use App\Module;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // return view("student.index", ["students" => Student::all(), "search" => null]);

        $student = Student::all();
        $search = $request->get("search");
        if ($search) {
            $student = Student::where('lastname', 'like', '%' . $search . '%')
            ->orWhere('firstname', 'like', '%' . $search . '%')
            ->orWhere('email', 'like', '%' . $search . '%')
            ->get();
        // } elseif ($search) {
        //     $promotion = Promotion::where('name', 'like', '%' . $search . '%')
        //     ->orWhere('speciality', 'like', '%' . $search . '%')
        //     ->get();
        // }elseif ($search) {
        //     $module = Module::where('name', 'like', '%' . $search . '%')
        //     ->get();
        } else {
            $student = Student::all();
            // $promotion = Promotion::all();
            // $module = Module::all();
        }

        // return view("student.index", ["student" => $student, "promotions" => $promotion, "modules" => $module, "search" => $search]);
        return view("student.index", ["student" => $student, "search" => $search]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, Promotion $promotion)
    {
        $promotion_id = $request->input("promotion");

        // return view(
        //     "student.create",
        //     ["promotion" => Promotion::find($promotion_id)]
        // );

        $id = $request->input('id');
        return view (
            "student.createstud",
            [
                "id" => $id,
                "promotion" => Promotion::find($promotion_id)
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        // $newStudent = new Student();
        // $newStudent->lastname = $request->input("lastname");
        // $newStudent->firstname = $request->input("firstname");
        // $newStudent->email = $request->input("email");
        // $newStudent->promotion_id = $request->input("promotion_id");
        // $newStudent->save();

        // return redirect()->route("student.index");

        $student = new Student;
        $student->lastname = $request->input('lastname');
        $student->firstname = $request->input('firstname');
        $student->email = $request->input('email');
        $student->promotion_id = $request->input('promotion_id');
        $student->save();

        $promotion = Promotion::find($request->input('promotion_id'));
        return redirect()->route('promotion.show', ['promotion' => $promotion]);
    }

    public function storeModules(Request $request)
    {
        $student = Student::find($request->input("student_id"));
        $student->modules()->detach();
        $student->modules()->attach($request->input("modules"));

        return redirect()->route("module.index", ["student" => $student->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student): View
    {
        return view("student.show", ["student" => $student]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student): View
    {
        $promotion = Promotion::All();
        return view("student.edit", ['student' => $student, 'promotion' => $promotion]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $lastname = $request->input('lastname');
        $firstname = $request->input('firstname');
        $email = $request->input('email');
        $promotion_id = $request->input('promotion');

        $student = Student::find($student->id);
        $student->lastname = $lastname;
        $student->firstname = $firstname;
        $student->email = $email;
        $student->promotion_id = $promotion_id;
        $student->push();
        return redirect()->route('student.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('student.index');
    }
}

resources/views/student/create.blade.php
@extends("student.form")
@section("page-title")Add Student @endsection
@section("action")
	{{ route("student.store") }}
@endsection
@section('promotion'){{ $promotion->name." ".$promotion->speciality }}@endsection
@section('promotion_id'){{ $promotion->id }}@endsection

resources/views/student/createstud.blade.php
@extends("student.formstud")
@section("page-title")Add Student @endsection
@section("action")
	{{ route("student.store") }}
@endsection
@section('promotion'){{ $promotion->name." ".$promotion->speciality }}@endsection
@section('promotion_id'){{ $promotion->id }}@endsection

resources/views/student/edit.blade.php
@extends("student.form")
@section("page-title")
    Add Student
@endsection
@section("action"){{ route("student.update", $student) }}@endsection
@section("method") @method("PUT") @endsection
@section("lastname"){{ $student->lastname }}@endsection
@section("firstname"){{ $student->firstname }}@endsection
@section("email"){{ $student->email }}@endsection
@section("promotion")
    <select name="promotion" class="form-control">
        @foreach ($promotion as $promo)
            <option value="{{ $promo->id }}">{{ $promo->name." ".$promo->speciality }}</option>
        @endforeach
    </select>
@endsection

resources/views/student/form.blade.php
@extends('application')
@section('page-title')
    @yield('page-title')
@endsection
@section('page-content')
    <div class="container mb-5 mt-3">
        <form method="post" action="@yield('action')">
            @csrf
            @method("put")
            <div class="form-row">
                <div class="col">
                    <label for="lastname">Lastname</label>
                    <input type="text" class="form-control" name="lastname" id="lastname" value="@yield("lastname")">
                </div>
                <div class="col">
                    <label for="firstname">Firstname</label>
                    <input type="text" class="form-control" name="firstname" id="firstname" value="@yield("firstname")">
                </div>
                <div class="col">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" id="email" value="@yield("email")">
                </div>
            </div>
            <label for="promotion">Promotion</label>
            <fieldset>
                <div class="form-row mb-5">
                  <div class="col">
                    @yield("promotion")
                  </div>
                </div>
            </fieldset>
            <input type="hidden" name="promotion_id" value="@yield("promotion_id")">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/student/formstud.blade.php
@extends('application')
@section('page-title')
    @yield('page-title')
@endsection
@section('page-content')
    <div class="container mb-5 mt-3">
        <form method="post" action="@yield('action')">
            @csrf
            <div class="form-row">
                <div class="col">
                    <label for="lastname">Lastname</label>
                    <input type="text" class="form-control" name="lastname" id="lastname" value="@yield("lastname")">
                </div>
                <div class="col">
                    <label for="firstname">Firstname</label>
                    <input type="text" class="form-control" name="firstname" id="firstname" value="@yield("firstname")">
                </div>
                <div class="col">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" id="email" value="@yield("email")">
                </div>
            </div>
            <label for="promotion">Promotion</label>
            <fieldset>
                <div class="form-row mb-5">
                  <div class="col">
                    @yield("promotion")
                  </div>
                </div>
            </fieldset>
            <input type="hidden" name="promotion_id" value="@yield("promotion_id")">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/student/index.blade.php
@extends('application')
@section('page-title')
    List
@endsection
@section('page-content')
    <div class="container">

        @if($search)
            <p class="mt-3">Search result for: {{ $search }}</p>
            <a href="{{route("student.index")}}" class="mb-5">Return to list</a>
        @endif

        <table class="table table-bordered mt-3">
            <thead>
            <tr>
                <th scope="col">Lastname</th>
                <th scope="col">Firstname</th>
                <th scope="col">Email</th>
                <th scope="col">Promotion</th>
                <th scope="col">Modules List</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>

            @foreach($student as $stud)
                <tr>
                    <td>{{ $stud->lastname }}</td>
                    <td>{{ $stud->firstname }}</td>
                    <td>{{ $stud->email }}</td>
                    <td>{{ $stud->promotion->name." ".$stud->promotion->speciality }}</td>
                    <td>
                        @foreach($stud->modules as $modu)
					        <li class="list-group" aria-current="true">{{ $modu->name }}</li>
                        @endforeach
                    </td>
                    
                    <td class="d-flex" style="size: inherit">
                        <a class="btn btn-outline-success mr-2" href="{{ route("student.show", $stud) }}">Show</a>
                        <a class="btn btn-outline-info mr-2" href="{{ route("student.edit", $stud) }}">Edit</a>
                        <form action="{{ route("student.destroy", $stud->id) }}" method="post">
                            <input class="btn btn-outline-danger" type="submit" value="Delete"/>
                            @method('delete')
                            @csrf
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
@endsection

resources/views/student/show.blade.php
@extends('application')
@section('page-title')
    {{ $student->lastname }} {{ $student->firstname }}
@endsection

@section('page-content')
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ $student->lastname }} {{ $student->firstname }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ $student->promotion->name." ".$student->promotion->speciality }}</h6>
                <p class="card-text">
                    <strong>Email: </strong>
                    {{ $student->email }}
                </p>
                <p class="card-text">
                    <strong>Modules: </strong>
                </p>
                <ul class="list-group list-group-flush mb-3">
                    @foreach($student->modules as $modu)
                        <li class="list-group-item">
                            <a href="{{ route("module.show", $modu) }}">{{ $modu->name }}</a>
                        </li>
                    @endforeach
                </ul>
                <div class="d-flex">
                    <a class="btn btn-outline-primary mr-2" href="{{ route("module.index", ["student"=>$student]) }}">Add Modules</a>
                    <a class="btn btn-outline-info mr-2" href="{{ route("student.edit", $student) }}">Edit</a>
                    <form action="{{ route("student.destroy", $student->id) }}" method="post">
                        <input class="btn btn-outline-danger" type="submit" value="Delete"/>
                        @method('delete')
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection